DROP TABLE Ashley.ITEM_INFO;
DROP TABLE Ashley.USER_INFO;
DROP TABLE Ashley.TYPE_INFO;
DROP TABLE Ashley.TAG_INFO;
DROP TABLE Ashley.CATEGORY_INFO;
DROP TABLE Ashley.AUTHOR_INFO;
DROP TABLE Ashley.RECOMMEND;
DROP TABLE Ashley.ITEM_COMMENT;